bits
32
stack_size
512
global_length
352
literal
0 0 0 0 1 0 0 0 255 255 255 255 7 0 0 0 79 0 98 0 106 0 101 0 99 0 116 0 64 0 3 0 0 0 10 0 0 0 6 0 0 0 1 0 0 0 46 0 1 0 0 0 98 0 0 0 0 0 1 0 0 0 48 0 45 0 48 0 0 0 97 2 0 0 0 120 0 121 0 33 0 0 0
classes
class E:\GitHub\tpl2\lib\lang.tp$Object $576
mro
methods
    E:\GitHub\tpl2\lib\lang.tp$Object.__new__()
    E:\GitHub\tpl2\lib\lang.tp$Object.__del__()
    E:\GitHub\tpl2\lib\lang.tp$Object.hash()
    E:\GitHub\tpl2\lib\lang.tp$Object.equals(*Object)
    E:\GitHub\tpl2\lib\lang.tp$Object.toString()
endclass

class E:\GitHub\tpl2\lib\lang.tp$String $580
mro
    E:\GitHub\tpl2\lib\lang.tp$Object
methods
    E:\GitHub\tpl2\lib\lang.tp$Object.__new__()
    E:\GitHub\tpl2\lib\lang.tp$String.__del__()
    E:\GitHub\tpl2\lib\lang.tp$Object.hash()
    E:\GitHub\tpl2\lib\lang.tp$String.equals(*Object)
    E:\GitHub\tpl2\lib\lang.tp$Object.toString()
    E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    E:\GitHub\tpl2\lib\lang.tp$String.__new__(*String)
    E:\GitHub\tpl2\lib\lang.tp$String.concat(*String)
    E:\GitHub\tpl2\lib\lang.tp$String.length()
    E:\GitHub\tpl2\lib\lang.tp$String.join(*String[])
    E:\GitHub\tpl2\lib\lang.tp$String.print()
    E:\GitHub\tpl2\lib\lang.tp$String.println()
endclass

class E:\GitHub\tpl2\lib\lang.tp$Number $584
mro
    E:\GitHub\tpl2\lib\lang.tp$Object
methods
    E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    E:\GitHub\tpl2\lib\lang.tp$Object.__del__()
    E:\GitHub\tpl2\lib\lang.tp$Object.hash()
    E:\GitHub\tpl2\lib\lang.tp$Object.equals(*Object)
    E:\GitHub\tpl2\lib\lang.tp$Object.toString()
    E:\GitHub\tpl2\lib\lang.tp$Number.intValue()
    E:\GitHub\tpl2\lib\lang.tp$Number.floatValue()
    E:\GitHub\tpl2\lib\lang.tp$Number.charValue()
    E:\GitHub\tpl2\lib\lang.tp$Number.byteValue()
endclass

class E:\GitHub\tpl2\lib\lang.tp$Integer $588
mro
    E:\GitHub\tpl2\lib\lang.tp$Number
    E:\GitHub\tpl2\lib\lang.tp$Object
methods
    E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    E:\GitHub\tpl2\lib\lang.tp$Object.__del__()
    E:\GitHub\tpl2\lib\lang.tp$Object.hash()
    E:\GitHub\tpl2\lib\lang.tp$Object.equals(*Object)
    E:\GitHub\tpl2\lib\lang.tp$Integer.toString()
    E:\GitHub\tpl2\lib\lang.tp$Integer.intValue()
    E:\GitHub\tpl2\lib\lang.tp$Integer.floatValue()
    E:\GitHub\tpl2\lib\lang.tp$Integer.charValue()
    E:\GitHub\tpl2\lib\lang.tp$Integer.byteValue()
    E:\GitHub\tpl2\lib\lang.tp$Integer.__new__(int)
endclass

class E:\GitHub\tpl2\lib\lang.tp$Float $592
mro
    E:\GitHub\tpl2\lib\lang.tp$Number
    E:\GitHub\tpl2\lib\lang.tp$Object
methods
    E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    E:\GitHub\tpl2\lib\lang.tp$Object.__del__()
    E:\GitHub\tpl2\lib\lang.tp$Object.hash()
    E:\GitHub\tpl2\lib\lang.tp$Object.equals(*Object)
    E:\GitHub\tpl2\lib\lang.tp$Float.toString()
    E:\GitHub\tpl2\lib\lang.tp$Float.intValue()
    E:\GitHub\tpl2\lib\lang.tp$Float.floatValue()
    E:\GitHub\tpl2\lib\lang.tp$Float.charValue()
    E:\GitHub\tpl2\lib\lang.tp$Float.byteValue()
    E:\GitHub\tpl2\lib\lang.tp$Float.__new__(float)
endclass

class E:\GitHub\tpl2\lib\lang.tp$Char $596
mro
    E:\GitHub\tpl2\lib\lang.tp$Number
    E:\GitHub\tpl2\lib\lang.tp$Object
methods
    E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    E:\GitHub\tpl2\lib\lang.tp$Object.__del__()
    E:\GitHub\tpl2\lib\lang.tp$Object.hash()
    E:\GitHub\tpl2\lib\lang.tp$Object.equals(*Object)
    E:\GitHub\tpl2\lib\lang.tp$Char.toString()
    E:\GitHub\tpl2\lib\lang.tp$Char.intValue()
    E:\GitHub\tpl2\lib\lang.tp$Char.floatValue()
    E:\GitHub\tpl2\lib\lang.tp$Char.charValue()
    E:\GitHub\tpl2\lib\lang.tp$Char.byteValue()
    E:\GitHub\tpl2\lib\lang.tp$Char.__new__(char)
endclass

class E:\GitHub\tpl2\lib\lang.tp$Byte $600
mro
    E:\GitHub\tpl2\lib\lang.tp$Number
    E:\GitHub\tpl2\lib\lang.tp$Object
methods
    E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    E:\GitHub\tpl2\lib\lang.tp$Object.__del__()
    E:\GitHub\tpl2\lib\lang.tp$Object.hash()
    E:\GitHub\tpl2\lib\lang.tp$Object.equals(*Object)
    E:\GitHub\tpl2\lib\lang.tp$Byte.toString()
    E:\GitHub\tpl2\lib\lang.tp$Byte.intValue()
    E:\GitHub\tpl2\lib\lang.tp$Byte.floatValue()
    E:\GitHub\tpl2\lib\lang.tp$Byte.charValue()
    E:\GitHub\tpl2\lib\lang.tp$Byte.byteValue()
    E:\GitHub\tpl2\lib\lang.tp$Byte.__new__(byte)
endclass

class E:\GitHub\tpl2\tp\heap.tp$Clazz $680
mro
    E:\GitHub\tpl2\lib\lang.tp$Object
methods
    E:\GitHub\tpl2\tp\heap.tp$Clazz.__new__()
    E:\GitHub\tpl2\lib\lang.tp$Object.__del__()
    E:\GitHub\tpl2\lib\lang.tp$Object.hash()
    E:\GitHub\tpl2\lib\lang.tp$Object.equals(*Object)
    E:\GitHub\tpl2\lib\lang.tp$Object.toString()
endclass


fn E:\GitHub\tpl2\lib\lang.tp$Object.__new__() $688
    push_fp
    push          4
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Object.__del__() $692
    push_fp
    push          4
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Object.hash() $696
    push_fp
    push          24
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      0
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    load          %0      $0
    iload         %1      $20
    store         %1      %0
    load          %0      $20
    iload         %1      $16
    store         %1      %0
    load          %0      $12
    load          %1      $16
    muli          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Object.equals(*Object) $700
    push_fp
    push          12
    load          %0      $0
    load          %1      $4
    eqi           %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Object.toString() $704
    push_fp
    push          20
    require       malloc  $8      %0      %1
    iload         %0      $8
    iload         %1      $12
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $12
    store_abs     %0      %1
    iload         %0      4
    set_ret       %0
    invoke        $8
    load          %0      $4
    iload         %1      580
    store_abs     %0      %1
    lit_abs       %0      $12
    iload         %1      $16
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $4
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $16
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[]) $708
    push_fp
    push          12
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Object.__new__()
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    load          %1      $4
    store_abs     %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.__new__(*String) $712
    push_fp
    push          20
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Object.__new__()
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $4
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rload_abs     %1      %0
    iload         %0      16
    store         %0      %1
    load          %0      $8
    load          %1      $16
    store_abs     %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.__del__() $716
    push_fp
    push          36
    load          %0      $0
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rload_abs     %1      %0
    iload         %0      16
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $16
    store_abs     %0      %1
    iload         %0      8
    set_ret       %0
    invoke        $552
    load_lit      %0      $30
    iload         %1      $20
    store         %1      %0
    load          %0      $8
    load          %1      $20
    eqi           %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    if_zero_goto  %0      ENDIF_0
    pull_fp
    ret
    label         ENDIF_0
    require       free    $24     %0      %1
    load          %0      $0
    iload         %1      $28
    store         %1      %0
    load          %0      $28
    iload         %1      4
    addi          %0      %1
    iload         %1      28
    store         %1      %0
    load          %0      $28
    rload_abs     %1      %0
    iload         %0      32
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $32
    store_abs     %0      %1
    invoke        $24
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Object.__del__()
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.concat(*String) $720
    push_fp
    push          100
    iload         %0      $1
    iload         %1      $16
    store         %1      %0
    aload         %0      $16
    iload         %1      12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      24
    store         %1      %0
    load          %0      $0
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      32
    set_ret       %1
    call_reg      %0
    load          %0      $4
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $4
    store_abs     %1      %2
    iload         %1      36
    set_ret       %1
    call_reg      %0
    load          %0      $32
    load          %1      $36
    addi          %0      %1
    iload         %1      28
    store         %1      %0
    load          %0      $24
    load          %1      $28
    store_abs     %0      %1
    iload         %0      $2
    iload         %1      $40
    store         %1      %0
    require       heap_array $44     %0      %1
    aload_sp      %0      $0
    load          %1      $40
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $12
    store_abs     %0      %1
    iload         %0      8
    set_ret       %0
    invoke        $44
    load          %0      $0
    iload         %1      $48
    store         %1      %0
    load          %0      $48
    iload         %1      4
    addi          %0      %1
    iload         %1      48
    store         %1      %0
    load          %0      $48
    rload_abs     %1      %0
    iload         %0      52
    store         %0      %1
    load_lit      %0      $0
    iload         %1      $56
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $60
    store         %1      %0
    load          %0      $0
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      64
    set_ret       %1
    call_reg      %0
    aload_sp      %0      $0
    load          %1      $52
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $56
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $8
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $60
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $64
    store_abs     %0      %1
    call          $668
    load          %0      $4
    iload         %1      $68
    store         %1      %0
    load          %0      $68
    iload         %1      4
    addi          %0      %1
    iload         %1      68
    store         %1      %0
    load          %0      $68
    rload_abs     %1      %0
    iload         %0      72
    store         %0      %1
    load_lit      %0      $0
    iload         %1      $76
    store         %1      %0
    load          %0      $0
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      80
    set_ret       %1
    call_reg      %0
    load          %0      $4
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $4
    store_abs     %1      %2
    iload         %1      84
    set_ret       %1
    call_reg      %0
    aload_sp      %0      $0
    load          %1      $72
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $76
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $8
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $80
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $84
    store_abs     %0      %1
    call          $668
    require       malloc  $92     %0      %1
    iload         %0      $8
    iload         %1      $96
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $96
    store_abs     %0      %1
    iload         %0      88
    set_ret       %0
    invoke        $92
    load          %0      $88
    iload         %1      580
    store_abs     %0      %1
    aload_sp      %0      $0
    load          %1      $88
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $8
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $88
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.equals(*Object) $724
    push_fp
    push          100
    load          %0      $4
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      0
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rload_abs     %1      %0
    iload         %0      16
    store         %0      %1
    iload         %0      580
    load          %1      $16
    subclass      %0      %1      %2      %3
    iload         %1      8
    store         %1      %0
    load          %0      $8
    not           %0
    iload         %1      20
    store         %1      %0
    load          %0      $20
    if_zero_goto  %0      ENDIF_1
    load          %0      $560
    put_ret       %0
    pull_fp
    ret
    label         ENDIF_1
    load          %0      $4
    iload         %1      $24
    store         %1      %0
    load          %0      $0
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      32
    set_ret       %1
    call_reg      %0
    load          %0      $24
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $24
    store_abs     %1      %2
    iload         %1      36
    set_ret       %1
    call_reg      %0
    load          %0      $32
    load          %1      $36
    nei           %0      %1
    iload         %1      28
    store         %1      %0
    load          %0      $28
    if_zero_goto  %0      ENDIF_2
    load          %0      $560
    put_ret       %0
    pull_fp
    ret
    label         ENDIF_2
    load_lit      %0      $0
    iload         %1      $40
    store         %1      %0
    label         LOOP_TITLE_0
    load          %0      $0
    iload         %1      $52
    store         %1      %0
    load          %0      $52
    iload         %1      4
    addi          %0      %1
    iload         %1      52
    store         %1      %0
    load          %0      $52
    rload_abs     %1      %0
    iload         %0      56
    store         %0      %1
    load          %0      $56
    rload_abs     %1      %0
    iload         %0      48
    store         %0      %1
    load          %0      $40
    load          %1      $48
    lti           %0      %1
    iload         %1      44
    store         %1      %0
    load          %0      $44
    if_zero_goto  %0      END_LOOP_0
    load          %0      $0
    iload         %1      $66
    store         %1      %0
    load          %0      $66
    iload         %1      4
    addi          %0      %1
    iload         %1      66
    store         %1      %0
    load          %0      $66
    rload_abs     %1      %0
    iload         %0      70
    store         %0      %1
    load          %0      $40
    iload         %1      $74
    store         %1      %0
    load          %0      $74
    iload         %1      2
    muli          %0      %1
    iload         %1      74
    store         %1      %0
    load          %0      $74
    iload         %1      4
    addi          %0      %1
    iload         %1      74
    store         %1      %0
    load          %0      $70
    load          %1      $74
    addi          %0      %1
    iload         %1      74
    store         %1      %0
    load          %0      $74
    rloadc_abs    %1      %0
    iload         %0      64
    storec        %0      %1
    load          %0      $24
    iload         %1      $80
    store         %1      %0
    load          %0      $80
    iload         %1      4
    addi          %0      %1
    iload         %1      80
    store         %1      %0
    load          %0      $80
    rload_abs     %1      %0
    iload         %0      84
    store         %0      %1
    load          %0      $40
    iload         %1      $88
    store         %1      %0
    load          %0      $88
    iload         %1      2
    muli          %0      %1
    iload         %1      88
    store         %1      %0
    load          %0      $88
    iload         %1      4
    addi          %0      %1
    iload         %1      88
    store         %1      %0
    load          %0      $84
    load          %1      $88
    addi          %0      %1
    iload         %1      88
    store         %1      %0
    load          %0      $88
    rloadc_abs    %1      %0
    iload         %0      78
    storec        %0      %1
    loadc         %0      $64
    iload         %1      $92
    store         %1      %0
    loadc         %0      $78
    iload         %1      $96
    store         %1      %0
    load          %0      $92
    load          %1      $96
    nei           %0      %1
    iload         %1      60
    store         %1      %0
    load          %0      $60
    if_zero_goto  %0      ENDIF_3
    load          %0      $560
    put_ret       %0
    pull_fp
    ret
    label         ENDIF_3
    label         LABEL_0
    load          %0      $40
    iload         %1      1
    addi          %0      %1
    iload         %1      40
    store         %1      %0
    goto          LOOP_TITLE_0
    label         END_LOOP_0
    load          %0      $564
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.length() $728
    push_fp
    push          16
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    load          %0      $12
    rload_abs     %1      %0
    iload         %0      4
    store         %0      %1
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.join(*String[]) $732
    push_fp
    push          172
    load_lit      %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $0
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      16
    set_ret       %1
    call_reg      %0
    load          %0      $16
    iload         %1      $12
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $20
    store         %1      %0
    label         LOOP_TITLE_1
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      28
    store         %0      %1
    load          %0      $20
    load          %1      $28
    lti           %0      %1
    iload         %1      24
    store         %1      %0
    load          %0      $24
    if_zero_goto  %0      END_LOOP_1
    load          %0      $20
    iload         %1      $36
    store         %1      %0
    load          %0      $36
    iload         %1      4
    muli          %0      %1
    iload         %1      36
    store         %1      %0
    load          %0      $36
    iload         %1      4
    addi          %0      %1
    iload         %1      36
    store         %1      %0
    load          %0      $4
    load          %1      $36
    addi          %0      %1
    iload         %1      36
    store         %1      %0
    load          %0      $36
    rload_abs     %1      %0
    iload         %0      32
    store         %0      %1
    load          %0      $32
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $32
    store_abs     %1      %2
    iload         %1      40
    set_ret       %1
    call_reg      %0
    load          %0      $8
    load          %1      $40
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    label         LABEL_1
    load          %0      $20
    iload         %1      1
    addi          %0      %1
    iload         %1      20
    store         %1      %0
    goto          LOOP_TITLE_1
    label         END_LOOP_1
    load_lit      %0      $0
    iload         %1      $48
    store         %1      %0
    load          %0      $8
    load          %1      $48
    gti           %0      %1
    iload         %1      44
    store         %1      %0
    load          %0      $44
    if_zero_goto  %0      ENDIF_4
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      60
    store         %0      %1
    load_lit      %0      $4
    iload         %1      $64
    store         %1      %0
    load          %0      $60
    load          %1      $64
    subi          %0      %1
    iload         %1      56
    store         %1      %0
    load          %0      $12
    load          %1      $56
    muli          %0      %1
    iload         %1      52
    store         %1      %0
    load          %0      $8
    load          %1      $52
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    label         ENDIF_4
    iload         %0      $1
    iload         %1      $76
    store         %1      %0
    aload         %0      $76
    iload         %1      72
    store         %1      %0
    load          %0      $72
    iload         %1      4
    addi          %0      %1
    iload         %1      84
    store         %1      %0
    load          %0      $84
    load          %1      $8
    store_abs     %0      %1
    iload         %0      $2
    iload         %1      $88
    store         %1      %0
    require       heap_array $92     %0      %1
    aload_sp      %0      $0
    load          %1      $88
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $72
    store_abs     %0      %1
    iload         %0      68
    set_ret       %0
    invoke        $92
    load_lit      %0      $0
    iload         %1      $96
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $100
    store         %1      %0
    label         LOOP_TITLE_2
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      108
    store         %0      %1
    load          %0      $100
    load          %1      $108
    lti           %0      %1
    iload         %1      104
    store         %1      %0
    load          %0      $104
    if_zero_goto  %0      END_LOOP_2
    load          %0      $100
    iload         %1      $120
    store         %1      %0
    load          %0      $120
    iload         %1      4
    muli          %0      %1
    iload         %1      120
    store         %1      %0
    load          %0      $120
    iload         %1      4
    addi          %0      %1
    iload         %1      120
    store         %1      %0
    load          %0      $4
    load          %1      $120
    addi          %0      %1
    iload         %1      120
    store         %1      %0
    load          %0      $120
    rload_abs     %1      %0
    iload         %0      116
    store         %0      %1
    load          %0      $116
    iload         %1      $124
    store         %1      %0
    load          %0      $124
    iload         %1      4
    addi          %0      %1
    iload         %1      124
    store         %1      %0
    load          %0      $124
    rload_abs     %1      %0
    iload         %0      128
    store         %0      %1
    load          %0      $128
    iload         %1      $112
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $132
    store         %1      %0
    load          %0      $112
    rload_abs     %1      %0
    iload         %0      136
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $112
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $132
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $68
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $96
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $136
    store_abs     %0      %1
    call          $668
    load          %0      $112
    rload_abs     %1      %0
    iload         %0      140
    store         %0      %1
    load          %0      $96
    load          %1      $140
    addi          %0      %1
    iload         %1      96
    store         %1      %0
    load          %0      $96
    load          %1      $8
    lti           %0      %1
    iload         %1      144
    store         %1      %0
    load          %0      $144
    if_zero_goto  %0      ENDIF_5
    load          %0      $0
    iload         %1      $148
    store         %1      %0
    load          %0      $148
    iload         %1      4
    addi          %0      %1
    iload         %1      148
    store         %1      %0
    load          %0      $148
    rload_abs     %1      %0
    iload         %0      152
    store         %0      %1
    load_lit      %0      $0
    iload         %1      $156
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $152
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $156
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $68
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $96
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $12
    store_abs     %0      %1
    call          $668
    load          %0      $96
    load          %1      $12
    addi          %0      %1
    iload         %1      96
    store         %1      %0
    label         ENDIF_5
    label         LABEL_2
    load          %0      $100
    iload         %1      1
    addi          %0      %1
    iload         %1      100
    store         %1      %0
    goto          LOOP_TITLE_2
    label         END_LOOP_2
    require       malloc  $164    %0      %1
    iload         %0      $8
    iload         %1      $168
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $168
    store_abs     %0      %1
    iload         %0      160
    set_ret       %0
    invoke        $164
    load          %0      $160
    iload         %1      580
    store_abs     %0      %1
    aload_sp      %0      $0
    load          %1      $160
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $68
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $160
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.print() $736
    push_fp
    push          12
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      8
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $8
    store_abs     %0      %1
    invoke        $544
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.println() $740
    push_fp
    push          12
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      8
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $8
    store_abs     %0      %1
    invoke        $548
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Number.__new__() $744
    push_fp
    push          4
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Object.__new__()
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Number.intValue() $748 abstract

fn E:\GitHub\tpl2\lib\lang.tp$Number.floatValue() $752 abstract

fn E:\GitHub\tpl2\lib\lang.tp$Number.charValue() $756 abstract

fn E:\GitHub\tpl2\lib\lang.tp$Number.byteValue() $760 abstract

fn E:\GitHub\tpl2\lib\lang.tp$Integer.__new__(int) $764
    push_fp
    push          12
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    load          %1      $4
    store_abs     %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Integer.intValue() $768
    push_fp
    push          12
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      8
    store         %0      %1
    load          %0      $8
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Integer.floatValue() $772
    push_fp
    push          16
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    load          %0      $12
    i_to_f        %0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Integer.charValue() $776
    push_fp
    push          14
    load          %0      $0
    iload         %1      $6
    store         %1      %0
    load          %0      $6
    iload         %1      4
    addi          %0      %1
    iload         %1      6
    store         %1      %0
    load          %0      $6
    rload_abs     %1      %0
    iload         %0      10
    store         %0      %1
    load          %0      $10
    iload         %1      $4
    storec        %1      %0
    loadc         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Integer.byteValue() $780
    push_fp
    push          13
    load          %0      $0
    iload         %1      $5
    store         %1      %0
    load          %0      $5
    iload         %1      4
    addi          %0      %1
    iload         %1      5
    store         %1      %0
    load          %0      $5
    rload_abs     %1      %0
    iload         %0      9
    store         %0      %1
    load          %0      $9
    iload         %1      $4
    storeb        %1      %0
    loadb         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Integer.toString() $784
    push_fp
    push          16
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $12
    store_abs     %0      %1
    iload         %0      4
    set_ret       %0
    call          $656
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.__new__(float) $788
    push_fp
    push          12
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    load          %1      $4
    store_abs     %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.intValue() $792
    push_fp
    push          16
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    load          %0      $12
    f_to_i        %0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.floatValue() $796
    push_fp
    push          12
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      8
    store         %0      %1
    load          %0      $8
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.charValue() $800
    push_fp
    push          18
    load          %0      $0
    iload         %1      $10
    store         %1      %0
    load          %0      $10
    iload         %1      4
    addi          %0      %1
    iload         %1      10
    store         %1      %0
    load          %0      $10
    rload_abs     %1      %0
    iload         %0      14
    store         %0      %1
    load          %0      $14
    f_to_i        %0
    iload         %1      $6
    store         %1      %0
    load          %0      $6
    iload         %1      $4
    storec        %1      %0
    loadc         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.byteValue() $804
    push_fp
    push          17
    load          %0      $0
    iload         %1      $9
    store         %1      %0
    load          %0      $9
    iload         %1      4
    addi          %0      %1
    iload         %1      9
    store         %1      %0
    load          %0      $9
    rload_abs     %1      %0
    iload         %0      13
    store         %0      %1
    load          %0      $13
    f_to_i        %0
    iload         %1      $5
    store         %1      %0
    load          %0      $5
    iload         %1      $4
    storeb        %1      %0
    loadb         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.toString() $808
    push_fp
    push          132
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    load          %0      $12
    f_to_i        %0
    iload         %1      $4
    store         %1      %0
    load          %0      $0
    iload         %1      $20
    store         %1      %0
    load          %0      $20
    iload         %1      4
    addi          %0      %1
    iload         %1      20
    store         %1      %0
    load          %0      $20
    rload_abs     %1      %0
    iload         %0      24
    store         %0      %1
    load          %0      $4
    i_to_f        %0
    iload         %1      $28
    store         %1      %0
    load          %0      $24
    load          %1      $28
    subf          %0      %1
    iload         %1      16
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $36
    store         %1      %0
    load          %0      $36
    i_to_f        %0
    iload         %1      $40
    store         %1      %0
    load          %0      $16
    load          %1      $40
    ltf           %0      %1
    iload         %1      32
    store         %1      %0
    load          %0      $32
    if_zero_goto  %0      ELSE_6
    load          %0      $16
    negf          %0
    iload         %1      44
    store         %1      %0
    load          %0      $44
    iload         %1      $16
    store         %1      %0
    goto          ENDIF_6
    label         ELSE_6
    load          %0      $16
    iload         %1      $16
    store         %1      %0
    label         ENDIF_6
    load          %0      $4
    iload         %1      $52
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $52
    store_abs     %0      %1
    iload         %0      48
    set_ret       %0
    call          $656
    load_lit      %0      $0
    iload         %1      $56
    store         %1      %0
    label         LOOP_TITLE_3
    load_lit      %0      $38
    iload         %1      $68
    store         %1      %0
    load          %0      $56
    load          %1      $68
    lti           %0      %1
    iload         %1      64
    store         %1      %0
    load          %0      $64
    if_zero_goto  %0      ELSE_7
    load          %0      $16
    f_to_i        %0
    iload         %1      $76
    store         %1      %0
    load          %0      $76
    i_to_f        %0
    iload         %1      $80
    store         %1      %0
    load          %0      $16
    load          %1      $80
    nef           %0      %1
    iload         %1      72
    store         %1      %0
    load          %0      $72
    iload         %1      $60
    store         %1      %0
    goto          ENDIF_7
    label         ELSE_7
    load_lit      %0      $0
    iload         %1      $84
    store         %1      %0
    load          %0      $84
    iload         %1      $60
    store         %1      %0
    label         ENDIF_7
    load          %0      $60
    if_zero_goto  %0      END_LOOP_3
    load_lit      %0      $34
    iload         %1      $88
    store         %1      %0
    load          %0      $88
    i_to_f        %0
    iload         %1      $92
    store         %1      %0
    load          %0      $16
    load          %1      $92
    mulf          %0      %1
    iload         %1      16
    store         %1      %0
    load          %0      $56
    iload         %1      $96
    store         %1      %0
    load          %0      $56
    iload         %1      1
    addi          %0      %1
    iload         %1      56
    store         %1      %0
    goto          LOOP_TITLE_3
    label         END_LOOP_3
    load          %0      $16
    f_to_i        %0
    iload         %1      $104
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $104
    store_abs     %0      %1
    iload         %0      100
    set_ret       %0
    call          $656
    require       malloc  $116    %0      %1
    iload         %0      $8
    iload         %1      $120
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $120
    store_abs     %0      %1
    iload         %0      112
    set_ret       %0
    invoke        $116
    load          %0      $112
    iload         %1      580
    store_abs     %0      %1
    lit_abs       %0      $42
    iload         %1      $124
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $112
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $124
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $48
    iload         %1      7
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $48
    store_abs     %1      %2
    aload_sp      %1      $4
    load          %2      $112
    store_abs     %1      %2
    iload         %1      108
    set_ret       %1
    call_reg      %0
    load          %0      $108
    iload         %1      7
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $108
    store_abs     %1      %2
    aload_sp      %1      $4
    load          %2      $100
    store_abs     %1      %2
    iload         %1      128
    set_ret       %1
    call_reg      %0
    load          %0      $128
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.__new__(char) $812
    push_fp
    push          10
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    load          %0      $0
    iload         %1      $6
    store         %1      %0
    load          %0      $6
    iload         %1      4
    addi          %0      %1
    iload         %1      6
    store         %1      %0
    load          %0      $6
    load          %1      $4
    storec_abs    %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.intValue() $816
    push_fp
    push          14
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rloadc_abs    %1      %0
    iload         %0      12
    storec        %0      %1
    loadc         %0      $12
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.floatValue() $820
    push_fp
    push          18
    load          %0      $0
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rloadc_abs    %1      %0
    iload         %0      16
    storec        %0      %1
    loadc         %0      $16
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    i_to_f        %0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.charValue() $824
    push_fp
    push          10
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rloadc_abs    %1      %0
    iload         %0      8
    storec        %0      %1
    loadc         %0      $8
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.byteValue() $828
    push_fp
    push          15
    load          %0      $0
    iload         %1      $9
    store         %1      %0
    load          %0      $9
    iload         %1      4
    addi          %0      %1
    iload         %1      9
    store         %1      %0
    load          %0      $9
    rloadc_abs    %1      %0
    iload         %0      13
    storec        %0      %1
    loadc         %0      $13
    iload         %1      $5
    store         %1      %0
    load          %0      $5
    iload         %1      $4
    storeb        %1      %0
    loadb         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.toString() $832
    push_fp
    push          62
    iload         %0      $1
    iload         %1      $12
    store         %1      %0
    aload         %0      $12
    iload         %1      8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      20
    store         %1      %0
    load_lit      %0      $4
    iload         %1      $24
    store         %1      %0
    load          %0      $20
    load          %1      $24
    store_abs     %0      %1
    iload         %0      $2
    iload         %1      $28
    store         %1      %0
    require       heap_array $32     %0      %1
    aload_sp      %0      $0
    load          %1      $28
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $8
    store_abs     %0      %1
    iload         %0      4
    set_ret       %0
    invoke        $32
    load_lit      %0      $0
    iload         %1      $36
    store         %1      %0
    load          %0      $36
    iload         %1      $40
    store         %1      %0
    load          %0      $40
    iload         %1      2
    muli          %0      %1
    iload         %1      40
    store         %1      %0
    load          %0      $40
    iload         %1      4
    addi          %0      %1
    iload         %1      40
    store         %1      %0
    load          %0      $4
    load          %1      $40
    addi          %0      %1
    iload         %1      40
    store         %1      %0
    load          %0      $0
    iload         %1      $44
    store         %1      %0
    load          %0      $44
    iload         %1      4
    addi          %0      %1
    iload         %1      44
    store         %1      %0
    load          %0      $44
    rloadc_abs    %1      %0
    iload         %0      48
    storec        %0      %1
    load          %0      $40
    load          %1      $48
    storec_abs    %0      %1
    require       malloc  $54     %0      %1
    iload         %0      $8
    iload         %1      $58
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $58
    store_abs     %0      %1
    iload         %0      50
    set_ret       %0
    invoke        $54
    load          %0      $50
    iload         %1      580
    store_abs     %0      %1
    aload_sp      %0      $0
    load          %1      $50
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $4
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $50
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.__new__(byte) $836
    push_fp
    push          9
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    load          %0      $0
    iload         %1      $5
    store         %1      %0
    load          %0      $5
    iload         %1      4
    addi          %0      %1
    iload         %1      5
    store         %1      %0
    load          %0      $5
    load          %1      $4
    storeb_abs    %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.intValue() $840
    push_fp
    push          13
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rloadb_abs    %1      %0
    iload         %0      12
    storeb        %0      %1
    loadb         %0      $12
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.floatValue() $844
    push_fp
    push          17
    load          %0      $0
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rloadb_abs    %1      %0
    iload         %0      16
    storeb        %0      %1
    loadb         %0      $16
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    i_to_f        %0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.charValue() $848
    push_fp
    push          15
    load          %0      $0
    iload         %1      $10
    store         %1      %0
    load          %0      $10
    iload         %1      4
    addi          %0      %1
    iload         %1      10
    store         %1      %0
    load          %0      $10
    rloadb_abs    %1      %0
    iload         %0      14
    storeb        %0      %1
    loadb         %0      $14
    iload         %1      $6
    store         %1      %0
    load          %0      $6
    iload         %1      $4
    storec        %1      %0
    loadc         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.byteValue() $852
    push_fp
    push          9
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rloadb_abs    %1      %0
    iload         %0      8
    storeb        %0      %1
    loadb         %0      $8
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.toString() $856
    push_fp
    push          37
    load          %0      $0
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rloadb_abs    %1      %0
    iload         %0      16
    storeb        %0      %1
    loadb         %0      $16
    iload         %1      $8
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $8
    store_abs     %0      %1
    iload         %0      4
    set_ret       %0
    call          $656
    require       malloc  $25     %0      %1
    iload         %0      $8
    iload         %1      $29
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $29
    store_abs     %0      %1
    iload         %0      21
    set_ret       %0
    invoke        $25
    load          %0      $21
    iload         %1      580
    store_abs     %0      %1
    lit_abs       %0      $48
    iload         %1      $33
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $21
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $33
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $4
    iload         %1      7
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $4
    store_abs     %1      %2
    aload_sp      %1      $4
    load          %2      $21
    store_abs     %1      %2
    iload         %1      17
    set_ret       %1
    call_reg      %0
    load          %0      $17
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$println() $604
    push_fp
    push          16
    require       malloc  $4      %0      %1
    iload         %0      $8
    iload         %1      $8
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $8
    store_abs     %0      %1
    iload         %0      0
    set_ret       %0
    invoke        $4
    load          %0      $0
    iload         %1      580
    store_abs     %0      %1
    lit_abs       %0      $54
    iload         %1      $12
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $12
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call          $644
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$print(int) $608
    push_fp
    push          4
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    invoke        $512
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$println(int) $612
    push_fp
    push          4
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    invoke        $516
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$print(float) $616
    push_fp
    push          4
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    invoke        $520
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$println(float) $620
    push_fp
    push          4
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    invoke        $524
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$print(char) $624
    push_fp
    push          2
    aload_sp      %0      $0
    loadc         %1      $0
    store_abs     %0      %1
    invoke        $528
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$println(char) $628
    push_fp
    push          2
    aload_sp      %0      $0
    loadc         %1      $0
    store_abs     %0      %1
    invoke        $532
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$print(byte) $632
    push_fp
    push          1
    aload_sp      %0      $0
    loadb         %1      $0
    store_abs     %0      %1
    invoke        $536
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$println(byte) $636
    push_fp
    push          1
    aload_sp      %0      $0
    loadb         %1      $0
    store_abs     %0      %1
    invoke        $540
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$print(*String) $640
    push_fp
    push          4
    load          %0      $0
    iload         %1      10
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    call_reg      %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$println(*String) $644
    push_fp
    push          4
    load          %0      $0
    iload         %1      11
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    call_reg      %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$print(*Object) $648
    push_fp
    push          8
    load          %0      $0
    iload         %1      4
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      4
    set_ret       %1
    call_reg      %0
    aload_sp      %0      $0
    load          %1      $4
    store_abs     %0      %1
    call          $640
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$println(*Object) $652
    push_fp
    push          8
    load          %0      $0
    iload         %1      4
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      4
    set_ret       %1
    call_reg      %0
    aload_sp      %0      $0
    load          %1      $4
    store_abs     %0      %1
    call          $644
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$intToString(int) $656
    push_fp
    push          216
    load_lit      %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $0
    load          %1      $8
    eqi           %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    if_zero_goto  %0      ENDIF_8
    require       malloc  $16     %0      %1
    iload         %0      $8
    iload         %1      $20
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $20
    store_abs     %0      %1
    iload         %0      12
    set_ret       %0
    invoke        $16
    load          %0      $12
    iload         %1      580
    store_abs     %0      %1
    lit_abs       %0      $58
    iload         %1      $24
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $12
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $24
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $12
    put_ret       %0
    pull_fp
    ret
    label         ENDIF_8
    load_lit      %0      $0
    iload         %1      $36
    store         %1      %0
    load          %0      $0
    load          %1      $36
    lti           %0      %1
    iload         %1      32
    store         %1      %0
    load          %0      $32
    if_zero_goto  %0      ELSE_9
    load_lit      %0      $4
    iload         %1      $40
    store         %1      %0
    load          %0      $40
    negi          %0
    iload         %1      44
    store         %1      %0
    load          %0      $44
    iload         %1      $28
    store         %1      %0
    goto          ENDIF_9
    label         ELSE_9
    load_lit      %0      $4
    iload         %1      $48
    store         %1      %0
    load          %0      $48
    iload         %1      $28
    store         %1      %0
    label         ENDIF_9
    load          %0      $0
    load          %1      $28
    muli          %0      %1
    iload         %1      52
    store         %1      %0
    load_lit      %0      $4
    iload         %1      $64
    store         %1      %0
    load          %0      $28
    load          %1      $64
    eqi           %0      %1
    iload         %1      60
    store         %1      %0
    load          %0      $60
    if_zero_goto  %0      ELSE_10
    load_lit      %0      $0
    iload         %1      $68
    store         %1      %0
    load          %0      $68
    iload         %1      $56
    store         %1      %0
    goto          ENDIF_10
    label         ELSE_10
    load_lit      %0      $4
    iload         %1      $72
    store         %1      %0
    load          %0      $72
    iload         %1      $56
    store         %1      %0
    label         ENDIF_10
    load          %0      $52
    iload         %1      $76
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $80
    store         %1      %0
    load_lit      %0      $4
    iload         %1      $84
    store         %1      %0
    label         LOOP_TITLE_4
    load_lit      %0      $0
    iload         %1      $92
    store         %1      %0
    load          %0      $76
    load          %1      $92
    nei           %0      %1
    iload         %1      88
    store         %1      %0
    load          %0      $88
    if_zero_goto  %0      END_LOOP_4
    load_lit      %0      $34
    iload         %1      $96
    store         %1      %0
    load          %0      $76
    load          %1      $96
    divi          %0      %1
    iload         %1      76
    store         %1      %0
    load_lit      %0      $34
    iload         %1      $100
    store         %1      %0
    load          %0      $84
    load          %1      $100
    muli          %0      %1
    iload         %1      84
    store         %1      %0
    load          %0      $80
    iload         %1      $104
    store         %1      %0
    load          %0      $80
    iload         %1      1
    addi          %0      %1
    iload         %1      80
    store         %1      %0
    goto          LOOP_TITLE_4
    label         END_LOOP_4
    load_lit      %0      $34
    iload         %1      $108
    store         %1      %0
    load          %0      $84
    load          %1      $108
    divi          %0      %1
    iload         %1      84
    store         %1      %0
    iload         %0      $1
    iload         %1      $120
    store         %1      %0
    aload         %0      $120
    iload         %1      116
    store         %1      %0
    load          %0      $116
    iload         %1      4
    addi          %0      %1
    iload         %1      128
    store         %1      %0
    load          %0      $80
    load          %1      $56
    addi          %0      %1
    iload         %1      132
    store         %1      %0
    load          %0      $128
    load          %1      $132
    store_abs     %0      %1
    iload         %0      $2
    iload         %1      $136
    store         %1      %0
    require       heap_array $140    %0      %1
    aload_sp      %0      $0
    load          %1      $136
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $116
    store_abs     %0      %1
    iload         %0      112
    set_ret       %0
    invoke        $140
    load_lit      %0      $4
    iload         %1      $148
    store         %1      %0
    load          %0      $148
    negi          %0
    iload         %1      152
    store         %1      %0
    load          %0      $28
    load          %1      $152
    eqi           %0      %1
    iload         %1      144
    store         %1      %0
    load          %0      $144
    if_zero_goto  %0      ENDIF_11
    load_lit      %0      $0
    iload         %1      $156
    store         %1      %0
    load          %0      $156
    iload         %1      $160
    store         %1      %0
    load          %0      $160
    iload         %1      2
    muli          %0      %1
    iload         %1      160
    store         %1      %0
    load          %0      $160
    iload         %1      4
    addi          %0      %1
    iload         %1      160
    store         %1      %0
    load          %0      $112
    load          %1      $160
    addi          %0      %1
    iload         %1      160
    store         %1      %0
    loadc_lit     %0      $64
    iload         %1      $164
    storec        %1      %0
    load          %0      $160
    load          %1      $164
    storec_abs    %0      %1
    label         ENDIF_11
    load          %0      $52
    iload         %1      $76
    store         %1      %0
    load          %0      $56
    iload         %1      $166
    store         %1      %0
    label         LOOP_TITLE_5
    load          %0      $80
    load          %1      $56
    addi          %0      %1
    iload         %1      174
    store         %1      %0
    load          %0      $166
    load          %1      $174
    lti           %0      %1
    iload         %1      170
    store         %1      %0
    load          %0      $170
    if_zero_goto  %0      END_LOOP_5
    load          %0      $76
    load          %1      $84
    divi          %0      %1
    iload         %1      178
    store         %1      %0
    load          %0      $178
    load          %1      $84
    muli          %0      %1
    iload         %1      182
    store         %1      %0
    load          %0      $76
    load          %1      $182
    subi          %0      %1
    iload         %1      76
    store         %1      %0
    load          %0      $166
    iload         %1      $186
    store         %1      %0
    load          %0      $186
    iload         %1      2
    muli          %0      %1
    iload         %1      186
    store         %1      %0
    load          %0      $186
    iload         %1      4
    addi          %0      %1
    iload         %1      186
    store         %1      %0
    load          %0      $112
    load          %1      $186
    addi          %0      %1
    iload         %1      186
    store         %1      %0
    load_lit      %0      $66
    iload         %1      $196
    store         %1      %0
    load          %0      $178
    load          %1      $196
    addi          %0      %1
    iload         %1      192
    store         %1      %0
    load          %0      $192
    iload         %1      $190
    storec        %1      %0
    load          %0      $186
    load          %1      $190
    storec_abs    %0      %1
    load_lit      %0      $34
    iload         %1      $200
    store         %1      %0
    load          %0      $84
    load          %1      $200
    divi          %0      %1
    iload         %1      84
    store         %1      %0
    label         LABEL_3
    load          %0      $166
    iload         %1      1
    addi          %0      %1
    iload         %1      166
    store         %1      %0
    goto          LOOP_TITLE_5
    label         END_LOOP_5
    require       malloc  $208    %0      %1
    iload         %0      $8
    iload         %1      $212
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $212
    store_abs     %0      %1
    iload         %0      204
    set_ret       %0
    invoke        $208
    load          %0      $204
    iload         %1      580
    store_abs     %0      %1
    aload_sp      %0      $0
    load          %1      $204
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $112
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $204
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$arraycopy(int[],int,int[],int,int) $660
    push_fp
    push          44
    iload         %0      $4
    iload         %1      $20
    store         %1      %0
    load          %0      $0
    iload         %1      $24
    store         %1      %0
    load          %0      $4
    load          %1      $20
    muli          %0      %1
    iload         %1      28
    store         %1      %0
    load          %0      $8
    iload         %1      $32
    store         %1      %0
    load          %0      $12
    load          %1      $20
    muli          %0      %1
    iload         %1      36
    store         %1      %0
    load          %0      $16
    load          %1      $20
    muli          %0      %1
    iload         %1      40
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $24
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $28
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $32
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $36
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $40
    store_abs     %0      %1
    invoke        $556
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$arraycopy(float[],int,float[],int,int) $664
    push_fp
    push          44
    iload         %0      $4
    iload         %1      $20
    store         %1      %0
    load          %0      $0
    iload         %1      $24
    store         %1      %0
    load          %0      $4
    load          %1      $20
    muli          %0      %1
    iload         %1      28
    store         %1      %0
    load          %0      $8
    iload         %1      $32
    store         %1      %0
    load          %0      $12
    load          %1      $20
    muli          %0      %1
    iload         %1      36
    store         %1      %0
    load          %0      $16
    load          %1      $20
    muli          %0      %1
    iload         %1      40
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $24
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $28
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $32
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $36
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $40
    store_abs     %0      %1
    invoke        $556
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$arraycopy(char[],int,char[],int,int) $668
    push_fp
    push          44
    iload         %0      $2
    iload         %1      $20
    store         %1      %0
    load          %0      $0
    iload         %1      $24
    store         %1      %0
    load          %0      $4
    load          %1      $20
    muli          %0      %1
    iload         %1      28
    store         %1      %0
    load          %0      $8
    iload         %1      $32
    store         %1      %0
    load          %0      $12
    load          %1      $20
    muli          %0      %1
    iload         %1      36
    store         %1      %0
    load          %0      $16
    load          %1      $20
    muli          %0      %1
    iload         %1      40
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $24
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $28
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $32
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $36
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $40
    store_abs     %0      %1
    invoke        $556
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$arraycopy(byte[],int,byte[],int,int) $672
    push_fp
    push          28
    load          %0      $0
    iload         %1      $20
    store         %1      %0
    load          %0      $8
    iload         %1      $24
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $20
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $4
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $24
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $12
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $16
    store_abs     %0      %1
    invoke        $556
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$arraycopy(*Object[],int,*Object[],int,int) $676
    push_fp
    push          44
    iload         %0      $4
    iload         %1      $20
    store         %1      %0
    load          %0      $0
    iload         %1      $24
    store         %1      %0
    load          %0      $4
    load          %1      $20
    muli          %0      %1
    iload         %1      28
    store         %1      %0
    load          %0      $8
    iload         %1      $32
    store         %1      %0
    load          %0      $12
    load          %1      $20
    muli          %0      %1
    iload         %1      36
    store         %1      %0
    load          %0      $16
    load          %1      $20
    muli          %0      %1
    iload         %1      40
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $24
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $28
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $32
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $36
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $40
    store_abs     %0      %1
    invoke        $556
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\tp\heap.tp$Clazz.__new__() $860
    push_fp
    push          4
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Object.__new__()
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\tp\heap.tp$main() $684
    push_fp
    push          81
    require       malloc  $4      %0      %1
    iload         %0      $5
    iload         %1      $8
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $8
    store_abs     %0      %1
    iload         %0      0
    set_ret       %0
    invoke        $4
    load          %0      $0
    iload         %1      680
    store_abs     %0      %1
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\tp\heap.tp$Clazz.__new__()
    load          %0      $0
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    loadb_lit     %0      $70
    iload         %1      $16
    storeb        %1      %0
    load          %0      $12
    load          %1      $16
    storeb_abs    %0      %1
    iload         %0      $1
    iload         %1      $25
    store         %1      %0
    aload         %0      $25
    iload         %1      21
    store         %1      %0
    load          %0      $21
    iload         %1      4
    addi          %0      %1
    iload         %1      33
    store         %1      %0
    load_lit      %0      $71
    iload         %1      $37
    store         %1      %0
    load          %0      $33
    load          %1      $37
    store_abs     %0      %1
    iload         %0      $2
    iload         %1      $41
    store         %1      %0
    require       heap_array $45     %0      %1
    aload_sp      %0      $0
    load          %1      $41
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $21
    store_abs     %0      %1
    iload         %0      17
    set_ret       %0
    invoke        $45
    load_lit      %0      $0
    iload         %1      $49
    store         %1      %0
    load          %0      $49
    iload         %1      $53
    store         %1      %0
    load          %0      $53
    iload         %1      2
    muli          %0      %1
    iload         %1      53
    store         %1      %0
    load          %0      $53
    iload         %1      4
    addi          %0      %1
    iload         %1      53
    store         %1      %0
    load          %0      $17
    load          %1      $53
    addi          %0      %1
    iload         %1      53
    store         %1      %0
    loadc_lit     %0      $75
    iload         %1      $57
    storec        %1      %0
    load          %0      $53
    load          %1      $57
    storec_abs    %0      %1
    load_lit      %0      $4
    iload         %1      $59
    store         %1      %0
    load          %0      $59
    iload         %1      $63
    store         %1      %0
    load          %0      $63
    iload         %1      2
    muli          %0      %1
    iload         %1      63
    store         %1      %0
    load          %0      $63
    iload         %1      4
    addi          %0      %1
    iload         %1      63
    store         %1      %0
    load          %0      $17
    load          %1      $63
    addi          %0      %1
    iload         %1      63
    store         %1      %0
    loadc_lit     %0      $77
    iload         %1      $67
    storec        %1      %0
    load          %0      $63
    load          %1      $67
    storec_abs    %0      %1
    iload         %0      $5
    iload         %1      $73
    store         %1      %0
    load_lit      %0      $79
    iload         %1      $77
    store         %1      %0
    load          %0      $73
    load          %1      $77
    addi          %0      %1
    iload         %1      69
    store         %1      %0
    load          %0      $69
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Object.__new__() $688
    push_fp
    push          4
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Object.__del__() $692
    push_fp
    push          4
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Object.hash() $696
    push_fp
    push          24
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      0
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    load          %0      $0
    iload         %1      $20
    store         %1      %0
    load          %0      $20
    iload         %1      $16
    store         %1      %0
    load          %0      $12
    load          %1      $16
    muli          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Object.equals(*Object) $700
    push_fp
    push          12
    load          %0      $0
    load          %1      $4
    eqi           %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Object.toString() $704
    push_fp
    push          20
    require       malloc  $8      %0      %1
    iload         %0      $8
    iload         %1      $12
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $12
    store_abs     %0      %1
    iload         %0      4
    set_ret       %0
    invoke        $8
    load          %0      $4
    iload         %1      580
    store_abs     %0      %1
    lit_abs       %0      $12
    iload         %1      $16
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $4
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $16
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[]) $708
    push_fp
    push          12
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Object.__new__()
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    load          %1      $4
    store_abs     %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.__new__(*String) $712
    push_fp
    push          20
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Object.__new__()
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $4
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rload_abs     %1      %0
    iload         %0      16
    store         %0      %1
    load          %0      $8
    load          %1      $16
    store_abs     %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.__del__() $716
    push_fp
    push          36
    load          %0      $0
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rload_abs     %1      %0
    iload         %0      16
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $16
    store_abs     %0      %1
    iload         %0      8
    set_ret       %0
    invoke        $552
    load_lit      %0      $30
    iload         %1      $20
    store         %1      %0
    load          %0      $8
    load          %1      $20
    eqi           %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    if_zero_goto  %0      ENDIF_12
    pull_fp
    ret
    label         ENDIF_12
    require       free    $24     %0      %1
    load          %0      $0
    iload         %1      $28
    store         %1      %0
    load          %0      $28
    iload         %1      4
    addi          %0      %1
    iload         %1      28
    store         %1      %0
    load          %0      $28
    rload_abs     %1      %0
    iload         %0      32
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $32
    store_abs     %0      %1
    invoke        $24
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Object.__del__()
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.concat(*String) $720
    push_fp
    push          100
    iload         %0      $1
    iload         %1      $16
    store         %1      %0
    aload         %0      $16
    iload         %1      12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      24
    store         %1      %0
    load          %0      $0
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      32
    set_ret       %1
    call_reg      %0
    load          %0      $4
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $4
    store_abs     %1      %2
    iload         %1      36
    set_ret       %1
    call_reg      %0
    load          %0      $32
    load          %1      $36
    addi          %0      %1
    iload         %1      28
    store         %1      %0
    load          %0      $24
    load          %1      $28
    store_abs     %0      %1
    iload         %0      $2
    iload         %1      $40
    store         %1      %0
    require       heap_array $44     %0      %1
    aload_sp      %0      $0
    load          %1      $40
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $12
    store_abs     %0      %1
    iload         %0      8
    set_ret       %0
    invoke        $44
    load          %0      $0
    iload         %1      $48
    store         %1      %0
    load          %0      $48
    iload         %1      4
    addi          %0      %1
    iload         %1      48
    store         %1      %0
    load          %0      $48
    rload_abs     %1      %0
    iload         %0      52
    store         %0      %1
    load_lit      %0      $0
    iload         %1      $56
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $60
    store         %1      %0
    load          %0      $0
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      64
    set_ret       %1
    call_reg      %0
    aload_sp      %0      $0
    load          %1      $52
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $56
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $8
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $60
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $64
    store_abs     %0      %1
    call          $668
    load          %0      $4
    iload         %1      $68
    store         %1      %0
    load          %0      $68
    iload         %1      4
    addi          %0      %1
    iload         %1      68
    store         %1      %0
    load          %0      $68
    rload_abs     %1      %0
    iload         %0      72
    store         %0      %1
    load_lit      %0      $0
    iload         %1      $76
    store         %1      %0
    load          %0      $0
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      80
    set_ret       %1
    call_reg      %0
    load          %0      $4
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $4
    store_abs     %1      %2
    iload         %1      84
    set_ret       %1
    call_reg      %0
    aload_sp      %0      $0
    load          %1      $72
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $76
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $8
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $80
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $84
    store_abs     %0      %1
    call          $668
    require       malloc  $92     %0      %1
    iload         %0      $8
    iload         %1      $96
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $96
    store_abs     %0      %1
    iload         %0      88
    set_ret       %0
    invoke        $92
    load          %0      $88
    iload         %1      580
    store_abs     %0      %1
    aload_sp      %0      $0
    load          %1      $88
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $8
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $88
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.equals(*Object) $724
    push_fp
    push          100
    load          %0      $4
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      0
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rload_abs     %1      %0
    iload         %0      16
    store         %0      %1
    iload         %0      580
    load          %1      $16
    subclass      %0      %1      %2      %3
    iload         %1      8
    store         %1      %0
    load          %0      $8
    not           %0
    iload         %1      20
    store         %1      %0
    load          %0      $20
    if_zero_goto  %0      ENDIF_13
    load          %0      $560
    put_ret       %0
    pull_fp
    ret
    label         ENDIF_13
    load          %0      $4
    iload         %1      $24
    store         %1      %0
    load          %0      $0
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      32
    set_ret       %1
    call_reg      %0
    load          %0      $24
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $24
    store_abs     %1      %2
    iload         %1      36
    set_ret       %1
    call_reg      %0
    load          %0      $32
    load          %1      $36
    nei           %0      %1
    iload         %1      28
    store         %1      %0
    load          %0      $28
    if_zero_goto  %0      ENDIF_14
    load          %0      $560
    put_ret       %0
    pull_fp
    ret
    label         ENDIF_14
    load_lit      %0      $0
    iload         %1      $40
    store         %1      %0
    label         LOOP_TITLE_6
    load          %0      $0
    iload         %1      $52
    store         %1      %0
    load          %0      $52
    iload         %1      4
    addi          %0      %1
    iload         %1      52
    store         %1      %0
    load          %0      $52
    rload_abs     %1      %0
    iload         %0      56
    store         %0      %1
    load          %0      $56
    rload_abs     %1      %0
    iload         %0      48
    store         %0      %1
    load          %0      $40
    load          %1      $48
    lti           %0      %1
    iload         %1      44
    store         %1      %0
    load          %0      $44
    if_zero_goto  %0      END_LOOP_6
    load          %0      $0
    iload         %1      $66
    store         %1      %0
    load          %0      $66
    iload         %1      4
    addi          %0      %1
    iload         %1      66
    store         %1      %0
    load          %0      $66
    rload_abs     %1      %0
    iload         %0      70
    store         %0      %1
    load          %0      $40
    iload         %1      $74
    store         %1      %0
    load          %0      $74
    iload         %1      2
    muli          %0      %1
    iload         %1      74
    store         %1      %0
    load          %0      $74
    iload         %1      4
    addi          %0      %1
    iload         %1      74
    store         %1      %0
    load          %0      $70
    load          %1      $74
    addi          %0      %1
    iload         %1      74
    store         %1      %0
    load          %0      $74
    rloadc_abs    %1      %0
    iload         %0      64
    storec        %0      %1
    load          %0      $24
    iload         %1      $80
    store         %1      %0
    load          %0      $80
    iload         %1      4
    addi          %0      %1
    iload         %1      80
    store         %1      %0
    load          %0      $80
    rload_abs     %1      %0
    iload         %0      84
    store         %0      %1
    load          %0      $40
    iload         %1      $88
    store         %1      %0
    load          %0      $88
    iload         %1      2
    muli          %0      %1
    iload         %1      88
    store         %1      %0
    load          %0      $88
    iload         %1      4
    addi          %0      %1
    iload         %1      88
    store         %1      %0
    load          %0      $84
    load          %1      $88
    addi          %0      %1
    iload         %1      88
    store         %1      %0
    load          %0      $88
    rloadc_abs    %1      %0
    iload         %0      78
    storec        %0      %1
    loadc         %0      $64
    iload         %1      $92
    store         %1      %0
    loadc         %0      $78
    iload         %1      $96
    store         %1      %0
    load          %0      $92
    load          %1      $96
    nei           %0      %1
    iload         %1      60
    store         %1      %0
    load          %0      $60
    if_zero_goto  %0      ENDIF_15
    load          %0      $560
    put_ret       %0
    pull_fp
    ret
    label         ENDIF_15
    label         LABEL_4
    load          %0      $40
    iload         %1      1
    addi          %0      %1
    iload         %1      40
    store         %1      %0
    goto          LOOP_TITLE_6
    label         END_LOOP_6
    load          %0      $564
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.length() $728
    push_fp
    push          16
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    load          %0      $12
    rload_abs     %1      %0
    iload         %0      4
    store         %0      %1
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.join(*String[]) $732
    push_fp
    push          172
    load_lit      %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $0
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $0
    store_abs     %1      %2
    iload         %1      16
    set_ret       %1
    call_reg      %0
    load          %0      $16
    iload         %1      $12
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $20
    store         %1      %0
    label         LOOP_TITLE_7
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      28
    store         %0      %1
    load          %0      $20
    load          %1      $28
    lti           %0      %1
    iload         %1      24
    store         %1      %0
    load          %0      $24
    if_zero_goto  %0      END_LOOP_7
    load          %0      $20
    iload         %1      $36
    store         %1      %0
    load          %0      $36
    iload         %1      4
    muli          %0      %1
    iload         %1      36
    store         %1      %0
    load          %0      $36
    iload         %1      4
    addi          %0      %1
    iload         %1      36
    store         %1      %0
    load          %0      $4
    load          %1      $36
    addi          %0      %1
    iload         %1      36
    store         %1      %0
    load          %0      $36
    rload_abs     %1      %0
    iload         %0      32
    store         %0      %1
    load          %0      $32
    iload         %1      8
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $32
    store_abs     %1      %2
    iload         %1      40
    set_ret       %1
    call_reg      %0
    load          %0      $8
    load          %1      $40
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    label         LABEL_5
    load          %0      $20
    iload         %1      1
    addi          %0      %1
    iload         %1      20
    store         %1      %0
    goto          LOOP_TITLE_7
    label         END_LOOP_7
    load_lit      %0      $0
    iload         %1      $48
    store         %1      %0
    load          %0      $8
    load          %1      $48
    gti           %0      %1
    iload         %1      44
    store         %1      %0
    load          %0      $44
    if_zero_goto  %0      ENDIF_16
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      60
    store         %0      %1
    load_lit      %0      $4
    iload         %1      $64
    store         %1      %0
    load          %0      $60
    load          %1      $64
    subi          %0      %1
    iload         %1      56
    store         %1      %0
    load          %0      $12
    load          %1      $56
    muli          %0      %1
    iload         %1      52
    store         %1      %0
    load          %0      $8
    load          %1      $52
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    label         ENDIF_16
    iload         %0      $1
    iload         %1      $76
    store         %1      %0
    aload         %0      $76
    iload         %1      72
    store         %1      %0
    load          %0      $72
    iload         %1      4
    addi          %0      %1
    iload         %1      84
    store         %1      %0
    load          %0      $84
    load          %1      $8
    store_abs     %0      %1
    iload         %0      $2
    iload         %1      $88
    store         %1      %0
    require       heap_array $92     %0      %1
    aload_sp      %0      $0
    load          %1      $88
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $72
    store_abs     %0      %1
    iload         %0      68
    set_ret       %0
    invoke        $92
    load_lit      %0      $0
    iload         %1      $96
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $100
    store         %1      %0
    label         LOOP_TITLE_8
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      108
    store         %0      %1
    load          %0      $100
    load          %1      $108
    lti           %0      %1
    iload         %1      104
    store         %1      %0
    load          %0      $104
    if_zero_goto  %0      END_LOOP_8
    load          %0      $100
    iload         %1      $120
    store         %1      %0
    load          %0      $120
    iload         %1      4
    muli          %0      %1
    iload         %1      120
    store         %1      %0
    load          %0      $120
    iload         %1      4
    addi          %0      %1
    iload         %1      120
    store         %1      %0
    load          %0      $4
    load          %1      $120
    addi          %0      %1
    iload         %1      120
    store         %1      %0
    load          %0      $120
    rload_abs     %1      %0
    iload         %0      116
    store         %0      %1
    load          %0      $116
    iload         %1      $124
    store         %1      %0
    load          %0      $124
    iload         %1      4
    addi          %0      %1
    iload         %1      124
    store         %1      %0
    load          %0      $124
    rload_abs     %1      %0
    iload         %0      128
    store         %0      %1
    load          %0      $128
    iload         %1      $112
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $132
    store         %1      %0
    load          %0      $112
    rload_abs     %1      %0
    iload         %0      136
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $112
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $132
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $68
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $96
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $136
    store_abs     %0      %1
    call          $668
    load          %0      $112
    rload_abs     %1      %0
    iload         %0      140
    store         %0      %1
    load          %0      $96
    load          %1      $140
    addi          %0      %1
    iload         %1      96
    store         %1      %0
    load          %0      $96
    load          %1      $8
    lti           %0      %1
    iload         %1      144
    store         %1      %0
    load          %0      $144
    if_zero_goto  %0      ENDIF_17
    load          %0      $0
    iload         %1      $148
    store         %1      %0
    load          %0      $148
    iload         %1      4
    addi          %0      %1
    iload         %1      148
    store         %1      %0
    load          %0      $148
    rload_abs     %1      %0
    iload         %0      152
    store         %0      %1
    load_lit      %0      $0
    iload         %1      $156
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $152
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $156
    store_abs     %0      %1
    aload_sp      %0      $8
    load          %1      $68
    store_abs     %0      %1
    aload_sp      %0      $12
    load          %1      $96
    store_abs     %0      %1
    aload_sp      %0      $16
    load          %1      $12
    store_abs     %0      %1
    call          $668
    load          %0      $96
    load          %1      $12
    addi          %0      %1
    iload         %1      96
    store         %1      %0
    label         ENDIF_17
    label         LABEL_6
    load          %0      $100
    iload         %1      1
    addi          %0      %1
    iload         %1      100
    store         %1      %0
    goto          LOOP_TITLE_8
    label         END_LOOP_8
    require       malloc  $164    %0      %1
    iload         %0      $8
    iload         %1      $168
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $168
    store_abs     %0      %1
    iload         %0      160
    set_ret       %0
    invoke        $164
    load          %0      $160
    iload         %1      580
    store_abs     %0      %1
    aload_sp      %0      $0
    load          %1      $160
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $68
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $160
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.print() $736
    push_fp
    push          12
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      8
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $8
    store_abs     %0      %1
    invoke        $544
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$String.println() $740
    push_fp
    push          12
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      8
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $8
    store_abs     %0      %1
    invoke        $548
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Number.__new__() $744
    push_fp
    push          4
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Object.__new__()
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Number.intValue() $748 abstract

fn E:\GitHub\tpl2\lib\lang.tp$Number.floatValue() $752 abstract

fn E:\GitHub\tpl2\lib\lang.tp$Number.charValue() $756 abstract

fn E:\GitHub\tpl2\lib\lang.tp$Number.byteValue() $760 abstract

fn E:\GitHub\tpl2\lib\lang.tp$Integer.__new__(int) $764
    push_fp
    push          12
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    load          %1      $4
    store_abs     %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Integer.intValue() $768
    push_fp
    push          12
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      8
    store         %0      %1
    load          %0      $8
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Integer.floatValue() $772
    push_fp
    push          16
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    load          %0      $12
    i_to_f        %0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Integer.charValue() $776
    push_fp
    push          14
    load          %0      $0
    iload         %1      $6
    store         %1      %0
    load          %0      $6
    iload         %1      4
    addi          %0      %1
    iload         %1      6
    store         %1      %0
    load          %0      $6
    rload_abs     %1      %0
    iload         %0      10
    store         %0      %1
    load          %0      $10
    iload         %1      $4
    storec        %1      %0
    loadc         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Integer.byteValue() $780
    push_fp
    push          13
    load          %0      $0
    iload         %1      $5
    store         %1      %0
    load          %0      $5
    iload         %1      4
    addi          %0      %1
    iload         %1      5
    store         %1      %0
    load          %0      $5
    rload_abs     %1      %0
    iload         %0      9
    store         %0      %1
    load          %0      $9
    iload         %1      $4
    storeb        %1      %0
    loadb         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Integer.toString() $784
    push_fp
    push          16
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    aload_sp      %0      $0
    load          %1      $12
    store_abs     %0      %1
    iload         %0      4
    set_ret       %0
    call          $656
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.__new__(float) $788
    push_fp
    push          12
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    load          %1      $4
    store_abs     %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.intValue() $792
    push_fp
    push          16
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    load          %0      $12
    f_to_i        %0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.floatValue() $796
    push_fp
    push          12
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rload_abs     %1      %0
    iload         %0      8
    store         %0      %1
    load          %0      $8
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.charValue() $800
    push_fp
    push          18
    load          %0      $0
    iload         %1      $10
    store         %1      %0
    load          %0      $10
    iload         %1      4
    addi          %0      %1
    iload         %1      10
    store         %1      %0
    load          %0      $10
    rload_abs     %1      %0
    iload         %0      14
    store         %0      %1
    load          %0      $14
    f_to_i        %0
    iload         %1      $6
    store         %1      %0
    load          %0      $6
    iload         %1      $4
    storec        %1      %0
    loadc         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.byteValue() $804
    push_fp
    push          17
    load          %0      $0
    iload         %1      $9
    store         %1      %0
    load          %0      $9
    iload         %1      4
    addi          %0      %1
    iload         %1      9
    store         %1      %0
    load          %0      $9
    rload_abs     %1      %0
    iload         %0      13
    store         %0      %1
    load          %0      $13
    f_to_i        %0
    iload         %1      $5
    store         %1      %0
    load          %0      $5
    iload         %1      $4
    storeb        %1      %0
    loadb         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Float.toString() $808
    push_fp
    push          132
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rload_abs     %1      %0
    iload         %0      12
    store         %0      %1
    load          %0      $12
    f_to_i        %0
    iload         %1      $4
    store         %1      %0
    load          %0      $0
    iload         %1      $20
    store         %1      %0
    load          %0      $20
    iload         %1      4
    addi          %0      %1
    iload         %1      20
    store         %1      %0
    load          %0      $20
    rload_abs     %1      %0
    iload         %0      24
    store         %0      %1
    load          %0      $4
    i_to_f        %0
    iload         %1      $28
    store         %1      %0
    load          %0      $24
    load          %1      $28
    subf          %0      %1
    iload         %1      16
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $36
    store         %1      %0
    load          %0      $36
    i_to_f        %0
    iload         %1      $40
    store         %1      %0
    load          %0      $16
    load          %1      $40
    ltf           %0      %1
    iload         %1      32
    store         %1      %0
    load          %0      $32
    if_zero_goto  %0      ELSE_18
    load          %0      $16
    negf          %0
    iload         %1      44
    store         %1      %0
    load          %0      $44
    iload         %1      $16
    store         %1      %0
    goto          ENDIF_18
    label         ELSE_18
    load          %0      $16
    iload         %1      $16
    store         %1      %0
    label         ENDIF_18
    load          %0      $4
    iload         %1      $52
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $52
    store_abs     %0      %1
    iload         %0      48
    set_ret       %0
    call          $656
    load_lit      %0      $0
    iload         %1      $56
    store         %1      %0
    label         LOOP_TITLE_9
    load_lit      %0      $38
    iload         %1      $68
    store         %1      %0
    load          %0      $56
    load          %1      $68
    lti           %0      %1
    iload         %1      64
    store         %1      %0
    load          %0      $64
    if_zero_goto  %0      ELSE_19
    load          %0      $16
    f_to_i        %0
    iload         %1      $76
    store         %1      %0
    load          %0      $76
    i_to_f        %0
    iload         %1      $80
    store         %1      %0
    load          %0      $16
    load          %1      $80
    nef           %0      %1
    iload         %1      72
    store         %1      %0
    load          %0      $72
    iload         %1      $60
    store         %1      %0
    goto          ENDIF_19
    label         ELSE_19
    load_lit      %0      $0
    iload         %1      $84
    store         %1      %0
    load          %0      $84
    iload         %1      $60
    store         %1      %0
    label         ENDIF_19
    load          %0      $60
    if_zero_goto  %0      END_LOOP_9
    load_lit      %0      $34
    iload         %1      $88
    store         %1      %0
    load          %0      $88
    i_to_f        %0
    iload         %1      $92
    store         %1      %0
    load          %0      $16
    load          %1      $92
    mulf          %0      %1
    iload         %1      16
    store         %1      %0
    load          %0      $56
    iload         %1      $96
    store         %1      %0
    load          %0      $56
    iload         %1      1
    addi          %0      %1
    iload         %1      56
    store         %1      %0
    goto          LOOP_TITLE_9
    label         END_LOOP_9
    load          %0      $16
    f_to_i        %0
    iload         %1      $104
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $104
    store_abs     %0      %1
    iload         %0      100
    set_ret       %0
    call          $656
    require       malloc  $116    %0      %1
    iload         %0      $8
    iload         %1      $120
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $120
    store_abs     %0      %1
    iload         %0      112
    set_ret       %0
    invoke        $116
    load          %0      $112
    iload         %1      580
    store_abs     %0      %1
    lit_abs       %0      $42
    iload         %1      $124
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $112
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $124
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $48
    iload         %1      7
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $48
    store_abs     %1      %2
    aload_sp      %1      $4
    load          %2      $112
    store_abs     %1      %2
    iload         %1      108
    set_ret       %1
    call_reg      %0
    load          %0      $108
    iload         %1      7
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $108
    store_abs     %1      %2
    aload_sp      %1      $4
    load          %2      $100
    store_abs     %1      %2
    iload         %1      128
    set_ret       %1
    call_reg      %0
    load          %0      $128
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.__new__(char) $812
    push_fp
    push          10
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    load          %0      $0
    iload         %1      $6
    store         %1      %0
    load          %0      $6
    iload         %1      4
    addi          %0      %1
    iload         %1      6
    store         %1      %0
    load          %0      $6
    load          %1      $4
    storec_abs    %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.intValue() $816
    push_fp
    push          14
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rloadc_abs    %1      %0
    iload         %0      12
    storec        %0      %1
    loadc         %0      $12
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.floatValue() $820
    push_fp
    push          18
    load          %0      $0
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rloadc_abs    %1      %0
    iload         %0      16
    storec        %0      %1
    loadc         %0      $16
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    i_to_f        %0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.charValue() $824
    push_fp
    push          10
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rloadc_abs    %1      %0
    iload         %0      8
    storec        %0      %1
    loadc         %0      $8
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.byteValue() $828
    push_fp
    push          15
    load          %0      $0
    iload         %1      $9
    store         %1      %0
    load          %0      $9
    iload         %1      4
    addi          %0      %1
    iload         %1      9
    store         %1      %0
    load          %0      $9
    rloadc_abs    %1      %0
    iload         %0      13
    storec        %0      %1
    loadc         %0      $13
    iload         %1      $5
    store         %1      %0
    load          %0      $5
    iload         %1      $4
    storeb        %1      %0
    loadb         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Char.toString() $832
    push_fp
    push          62
    iload         %0      $1
    iload         %1      $12
    store         %1      %0
    aload         %0      $12
    iload         %1      8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      20
    store         %1      %0
    load_lit      %0      $4
    iload         %1      $24
    store         %1      %0
    load          %0      $20
    load          %1      $24
    store_abs     %0      %1
    iload         %0      $2
    iload         %1      $28
    store         %1      %0
    require       heap_array $32     %0      %1
    aload_sp      %0      $0
    load          %1      $28
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $8
    store_abs     %0      %1
    iload         %0      4
    set_ret       %0
    invoke        $32
    load_lit      %0      $0
    iload         %1      $36
    store         %1      %0
    load          %0      $36
    iload         %1      $40
    store         %1      %0
    load          %0      $40
    iload         %1      2
    muli          %0      %1
    iload         %1      40
    store         %1      %0
    load          %0      $40
    iload         %1      4
    addi          %0      %1
    iload         %1      40
    store         %1      %0
    load          %0      $4
    load          %1      $40
    addi          %0      %1
    iload         %1      40
    store         %1      %0
    load          %0      $0
    iload         %1      $44
    store         %1      %0
    load          %0      $44
    iload         %1      4
    addi          %0      %1
    iload         %1      44
    store         %1      %0
    load          %0      $44
    rloadc_abs    %1      %0
    iload         %0      48
    storec        %0      %1
    load          %0      $40
    load          %1      $48
    storec_abs    %0      %1
    require       malloc  $54     %0      %1
    iload         %0      $8
    iload         %1      $58
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $58
    store_abs     %0      %1
    iload         %0      50
    set_ret       %0
    invoke        $54
    load          %0      $50
    iload         %1      580
    store_abs     %0      %1
    aload_sp      %0      $0
    load          %1      $50
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $4
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $50
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.__new__(byte) $836
    push_fp
    push          9
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Number.__new__()
    load          %0      $0
    iload         %1      $5
    store         %1      %0
    load          %0      $5
    iload         %1      4
    addi          %0      %1
    iload         %1      5
    store         %1      %0
    load          %0      $5
    load          %1      $4
    storeb_abs    %0      %1
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.intValue() $840
    push_fp
    push          13
    load          %0      $0
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    iload         %1      4
    addi          %0      %1
    iload         %1      8
    store         %1      %0
    load          %0      $8
    rloadb_abs    %1      %0
    iload         %0      12
    storeb        %0      %1
    loadb         %0      $12
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.floatValue() $844
    push_fp
    push          17
    load          %0      $0
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rloadb_abs    %1      %0
    iload         %0      16
    storeb        %0      %1
    loadb         %0      $16
    iload         %1      $8
    store         %1      %0
    load          %0      $8
    i_to_f        %0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.charValue() $848
    push_fp
    push          15
    load          %0      $0
    iload         %1      $10
    store         %1      %0
    load          %0      $10
    iload         %1      4
    addi          %0      %1
    iload         %1      10
    store         %1      %0
    load          %0      $10
    rloadb_abs    %1      %0
    iload         %0      14
    storeb        %0      %1
    loadb         %0      $14
    iload         %1      $6
    store         %1      %0
    load          %0      $6
    iload         %1      $4
    storec        %1      %0
    loadc         %0      $4
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.byteValue() $852
    push_fp
    push          9
    load          %0      $0
    iload         %1      $4
    store         %1      %0
    load          %0      $4
    iload         %1      4
    addi          %0      %1
    iload         %1      4
    store         %1      %0
    load          %0      $4
    rloadb_abs    %1      %0
    iload         %0      8
    storeb        %0      %1
    loadb         %0      $8
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\lib\lang.tp$Byte.toString() $856
    push_fp
    push          37
    load          %0      $0
    iload         %1      $12
    store         %1      %0
    load          %0      $12
    iload         %1      4
    addi          %0      %1
    iload         %1      12
    store         %1      %0
    load          %0      $12
    rloadb_abs    %1      %0
    iload         %0      16
    storeb        %0      %1
    loadb         %0      $16
    iload         %1      $8
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $8
    store_abs     %0      %1
    iload         %0      4
    set_ret       %0
    call          $656
    require       malloc  $25     %0      %1
    iload         %0      $8
    iload         %1      $29
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $29
    store_abs     %0      %1
    iload         %0      21
    set_ret       %0
    invoke        $25
    load          %0      $21
    iload         %1      580
    store_abs     %0      %1
    lit_abs       %0      $48
    iload         %1      $33
    store         %1      %0
    aload_sp      %0      $0
    load          %1      $21
    store_abs     %0      %1
    aload_sp      %0      $4
    load          %1      $33
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$String.__new__(char[])
    load          %0      $4
    iload         %1      7
    iload         %2      0
    get_method    %0      %1      %2
    aload_sp      %1      $0
    load          %2      $4
    store_abs     %1      %2
    aload_sp      %1      $4
    load          %2      $21
    store_abs     %1      %2
    iload         %1      17
    set_ret       %1
    call_reg      %0
    load          %0      $17
    put_ret       %0
    pull_fp
    ret
    stop

fn E:\GitHub\tpl2\tp\heap.tp$Clazz.__new__() $860
    push_fp
    push          4
    aload_sp      %0      $0
    load          %1      $0
    store_abs     %0      %1
    call_fn       E:\GitHub\tpl2\lib\lang.tp$Object.__new__()
    pull_fp
    ret
    stop

entry
    require       print_int $512    %0      %1
    require       println_int $516    %0      %1
    require       print_float $520    %0      %1
    require       println_float $524    %0      %1
    require       print_char $528    %0      %1
    require       println_char $532    %0      %1
    require       print_byte $536    %0      %1
    require       println_byte $540    %0      %1
    require       print_str $544    %0      %1
    require       println_str $548    %0      %1
    require       mem_segment $552    %0      %1
    require       mem_copy $556    %0      %1
    load_lit      %0      $0
    iload         %1      $560
    store         %1      %0
    load_lit      %0      $4
    iload         %1      $564
    store         %1      %0
    load_lit      %0      $0
    iload         %1      $572
    store         %1      %0
    load          %0      $572
    iload         %1      $568
    store         %1      %0
    aload         %0      $1
    set_ret       %0
    call_fn       E:\GitHub\tpl2\tp\heap.tp$main()
    exit